### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by lucasBertola** [RUBYMAGE/angular-datepicker#10]
Hi,
can you update npm directory ? thx

**Comment by RUBYMAGE** [comment]
Hi,
What do you mean? Is not it updated?

**Comment by lucasBertola** [comment]
https://www.npmjs.com/package/rm-datepicker
Has you can see, last update was last year ago. but since, there is many "fix".
If you prefer, can you create a 1.0.1 release ?
thx

**Comment by RUBYMAGE** [comment]
Thank you for reporting this. Please be informed that a new release has
been published.

Best regards,
Sergiu
